services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: trustello_dev
      POSTGRES_USER: trustello
      POSTGRES_PASSWORD: trustello_dev_pw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  clamav:
    image: clamav/clamav:stable
    platform: linux/amd64
    ports:
      - "3310:3310"

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_MAX_MESSAGES: 5000

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
